use unicase::UniCase;

macro_rules! impl_keyword {
    ($(
			$value:ident => [$($key:tt),+$(,)?]
	),* $(,)?) => {
		#[derive(Clone,Copy,Eq,PartialEq,Hash,Debug)]
		pub enum Keyword{
			$($value,)*
			/// Not a keyword
			Identifier
		}

		impl Keyword{
			pub fn description(&self) -> &'static str{
				match *self{
					$(Self::$value => concat!("keyword `",impl_keyword!(@first [$($key),*]),"`"),)*
					Self::Identifier => "an identifier"
				}
			}
		}

		pub static KEYWORDS: phf::Map<UniCase<&'static str>,Keyword> = phf::phf_map! {
			$(
				$(UniCase::ascii($key) => Keyword::$value,)*
			)*
		};

    };

	(@first [$lit:tt $(,$tt:tt)*]) => {
		$lit
	};
}

impl_keyword! {
	Access => ["ACCESS"],
	After => ["AFTER"],
	Algorithm => ["ALGORITHM"],
	All => ["ALL"],
	Alter => ["ALTER"],
	Always => ["ALWAYS"],
	Analyze => ["ANALYZE"],
	Analyzer => ["ANALYZER"],
	Api => ["API"],
	As => ["AS"],
	Ascending => ["ASCENDING","ASC"],
	Ascii => ["ASCII"],
	Assert => ["ASSERT"],
	At => ["AT"],
	Authenticate => ["AUTHENTICATE"],
	Auto => ["AUTO"],
	Async => ["ASYNC"],
	Backend => ["BACKEND"],
	Batch => ["BATCH"],
	Bearer => ["BEARER"],
	Before => ["BEFORE"],
	Begin => ["BEGIN"],
	Blank => ["BLANK"],
	Bm25 => ["BM25"],
	Break => ["BREAK"],
	Bucket => ["BUCKET"],
	By => ["BY"],
	Camel => ["CAMEL"],
	Cancel => ["CANCEL"],
	Cascade => ["CASCADE"],
	ChangeFeed => ["CHANGEFEED"],
	Changes => ["CHANGES"],
	Capacity => ["CAPACITY"],
	Class => ["CLASS"],
	Comment => ["COMMENT"],
	Commit => ["COMMIT"],
	Compact => ["COMPACT"],
	Complexity => ["COMPLEXITY"],
	Computed => ["COMPUTED"],
	Concurrently => ["CONCURRENTLY"],
	Config => ["CONFIG"],
	Content => ["CONTENT"],
	Continue => ["CONTINUE"],
	Count => ["COUNT"],
	Create => ["CREATE"],
	Database => ["DATABASE","DB"],
	Default => ["DEFAULT"],
	Define => ["DEFINE"],
	Delete => ["DELETE"],
	Depth => ["DEPTH"],
	Descending => ["DESCENDING","DESC"],
	Diff => ["DIFF"],
	Dimension => ["DIMENSION"],
	Distance => ["DISTANCE"],
	DocIdsCache => ["DOCIDSCACHE"],
	DocIdsOrder => ["DOCIDSORDER"],
	DocLengthsCache => ["DOCLENGTHSCACHE"],
	DocLengthsOrder => ["DOCLENGTHSORDER"],
	Drop => ["DROP"],
	Duplicate => ["DUPLICATE"],
	Edgengram => ["EDGENGRAM"],
	Efc => ["EFC"],
	Event => ["EVENT"],
	Else => ["ELSE"],
	End => ["END"],
	Enforced => ["ENFORCED"],
	Exclude => ["EXCLUDE"],
	Exists => ["EXISTS"],
	Expired => ["EXPIRED"],
	Explain => ["EXPLAIN"],
	Expunge => ["EXPUNGE"],
	ExtendCandidates => ["EXTENDCANDIDATES"],
	False => ["FALSE"],
	Fetch => ["FETCH"],
	Field => ["FIELD","COLUMNS"],
	Fields => ["FIELDS"],
	Filters => ["FILTERS"],
	Flexible => ["FLEXIBLE"],
	For => ["FOR"],
	Format => ["FORMAT"],
	From => ["FROM"],
	Full => ["FULL"],
	Fulltext => ["FULLTEXT"],
	Function => ["FUNCTION"],
	Functions => ["FUNCTIONS"],
	Grant => ["GRANT"],
	Graphql => ["GRAPHQL"],
	Group => ["GROUP"],
	HashedVector => ["HASHEDVECTOR"],
	Headers => ["HEADERS"],
	Highlights => ["HIGHLIGHTS"],
	Hnsw => ["HNSW"],
	Ignore => ["IGNORE"],
	Include => ["INCLUDE"],
	Inclusive => ["INCLUSIVE"],
	Index => ["INDEX"],
	Info => ["INFO"],
	Insert => ["INSERT"],
	Into => ["INTO"],
	Introspection => ["INTROSPECTION"],
	If => ["IF"],
	Is => ["IS"],
	Issuer => ["ISSUER"],
	Jwt => ["JWT"],
	Jwks => ["JWKS"],
	Key => ["KEY"],
	KeepPrunedConnections => ["KEEPPRUNEDCONNECTIONS"],
	Kill => ["KILL"],
	Let => ["LET"],
	Limit => ["LIMIT"],
	Live => ["LIVE"],
	Lowercase => ["LOWERCASE"],
	Lm => ["LM"],
	M => ["M"],
	M0 => ["M0"],
	Mapper => ["MAPPER"],
	Maxdepth => ["MAXDEPTH"],
	Middleware => ["MIDDLEWARE"],
	ML => ["ML"],
	Merge => ["MERGE"],
	Model => ["MODEL"],
	Module => ["MODULE"],
	MTree => ["MTREE"],
	MTreeCache => ["MTREECACHE"],
	Namespace => ["NAMESPACE","NS"],
	Ngram => ["NGRAM"],
	No => ["NO"],
	NoIndex => ["NOINDEX"],
	None => ["NONE"],
	Null => ["NULL"],
	Numeric => ["NUMERIC"],
	Omit => ["OMIT"],
	On => ["ON"],
	Only => ["ONLY"],
	Option => ["OPTION"],
	Order => ["ORDER"],
	Original => ["ORIGINAL"],
	Overwrite => ["OVERWRITE"],
	Parallel => ["PARALLEL"],
	Param => ["PARAM"],
	Passhash => ["PASSHASH"],
	Password => ["PASSWORD"],
	Patch => ["PATCH"],
	Path => ["PATH"],
	Permissions => ["PERMISSIONS"],
	PostingsCache => ["POSTINGSCACHE"],
	PostingsOrder => ["POSTINGSORDER"],
	Prepare => ["PREPARE"],
	Punct => ["PUNCT"],
	Purge => ["PURGE"],
	Range => ["RANGE"],
	Readonly => ["READONLY"],
	Reject => ["REJECT"],
	Relate => ["RELATE"],
	Relation => ["RELATION"],
	Rebuild => ["REBUILD"],
	Reference => ["REFERENCE"],
	Refresh => ["REFRESH"],
	Remove => ["REMOVE"],
	Replace => ["REPLACE"],
	Retry => ["RETRY"],
	Return => ["RETURN"],
	Revoke => ["REVOKE"],
	Revoked => ["REVOKED"],
	Roles => ["ROLES"],
	Root => ["ROOT"],
	Schemafull => ["SCHEMAFULL"],
	Schemaless => ["SCHEMALESS"],
	Scope => ["SCOPE"],
	Search => ["SEARCH"],
	Select => ["SELECT"],
	Sequence => ["SEQUENCE"],
	Session => ["SESSION"],
	Set => ["SET"],
	Show => ["SHOW"],
	Shortest => ["SHORTEST"],
	Signin => ["SIGNIN"],
	Signup => ["SIGNUP"],
	Since => ["SINCE"],
	Sleep => ["SLEEP"],
	Snowball => ["SNOWBALL"],
	Split => ["SPLIT"],
	Start => ["START"],
	Strict => ["STRICT"],
	Structure => ["STRUCTURE"],
	System => ["SYSTEM"],
	Table => ["TABLE","TB"],
	Tables => ["TABLES"],
	TempFiles => ["TEMPFILES"],
	TermsCache => ["TERMSCACHE"],
	TermsOrder => ["TERMSORDER"],
	Text => ["TEXT"],
	Then => ["THEN"],
	Throw => ["THROW"],
	Timeout => ["TIMEOUT"],
	To => ["TO"],
	Tokenizers => ["TOKENIZERS"],
	Token => ["TOKEN"],
	Transaction => ["TRANSACTION"],

	QueryTimeout => ["QUERYTIMEOUT"],

	True => ["TRUE"],
	Type => ["TYPE"],
	Unique => ["UNIQUE"],
	Unset => ["UNSET"],
	Update => ["UPDATE"],
	Upsert => ["UPSERT"],
	Uppercase => ["UPPERCASE"],
	Url => ["URL"],
	Use => ["USE"],
	User => ["USER"],
	Value => ["VALUE"],
	Values => ["VALUES"],
	Version => ["VERSION"],
	Vs => ["VS"],
	When => ["WHEN"],
	Where => ["WHERE"],
	With => ["WITH"],
	AllInside => ["ALLINSIDE"],
	And => ["AND"],
	AnyInside => ["ANYINSIDE"],
	Inside => ["INSIDE"],
	Intersects => ["INTERSECTS"],
	Json => ["JSON"],
	NoneInside => ["NONEINSIDE"],
	NotInside => ["NOTINSIDE"],
	Or => ["OR"],
	Outside => ["OUTSIDE"],
	Not => ["NOT"],
	Collate => ["COLLATE"],
	ContainsAll => ["CONTAINSALL"],
	ContainsAny => ["CONTAINSANY"],
	ContainsNone => ["CONTAINSNONE"],
	ContainsNot => ["CONTAINSNOT"],
	Contains => ["CONTAINS"],
	In => ["IN"],
	Out => ["OUT"],
	Normal => ["NORMAL"],

		// Types
	Any => ["ANY"],
	Array => ["ARRAY"],
	Geometry => ["GEOMETRY"],
	Record => ["RECORD"],
	Bool => ["BOOL"],
	Bytes => ["BYTES"],
	Datetime => ["DATETIME"],
	Decimal => ["DECIMAL"],
	Duration => ["DURATION"],
	Float => ["FLOAT"],
	Int => ["INT"],
	Number => ["NUMBER"],
	Object => ["OBJECT"],
	Regex => ["REGEX"],
	String => ["STRING"],
	Uuid => ["UUID"],
	Ulid => ["ULID"],
	Rand => ["RAND"],
	References => ["REFERENCES"],
	Feature => ["FEATURE"],
	Line => ["LINE"],
	Point => ["POINT"],
	Polygon => ["POLYGON"],
	MultiPoint => ["MULTIPOINT"],
	MultiLine => ["MULTILINE"],
	MultiPolygon => ["MULTIPOLYGON"],
	Collect => ["COLLECT"],
	Collection => ["COLLECTION"],
	File => ["FILE"],

	EdDSA => ["EDDSA"],
	Es256 => ["ES256"],
	Es384 => ["ES384"],
	Es512 => ["ES512"],
	Hs256 => ["HS256"],
	Hs384 => ["HS384"],
	Hs512 => ["HS512"],
	Ps256 => ["PS256"],
	Ps384 => ["PS384"],
	Ps512 => ["PS512"],
	Rs256 => ["RS256"],
	Rs384 => ["RS384"],
	Rs512 => ["RS512"],

		// Distance
	Chebyshev => ["CHEBYSHEV"],
	Cosine => ["COSINE"],
	Euclidean => ["EUCLIDEAN"],
	Jaccard => ["JACCARD"],
	Hamming => ["HAMMING"],
	Manhattan => ["MANHATTAN"],
	Minkowski => ["MINKOWSKI"],
	Pearson => ["PEARSON"],

		// VectorTypes
	F64 => ["F64"],
	F32 => ["F32"],
	I64 => ["I64"],
	I32 => ["I32"],
	I16 => ["I16"],

		// HTTP methods
	Get => ["GET"],
	Post => ["POST"],
	Put => ["PUT"],
	Trace => ["TRACE"],
}

pub fn refine_keyword(slice: &str) -> Keyword {
	KEYWORDS.get(&UniCase::ascii(slice)).copied().unwrap_or(Keyword::Identifier)
}
